// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjffmweegagzhqcbdanq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqZmZtd2VlZ2FnemhxY2JkYW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDg5NTUsImV4cCI6MjA2MDYyNDk1NX0.Jf9L05FkxFA0i8Hns96yzpZk0G4L0unS0DqVVIqEnjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);